const EXECUTE = [
    {
        title: "Execute",
        content: [
            "Execute Task 1bdflblrbdaljkbadlkbdfklbdfkljbadfklbfkbdfjkbfkdjbakjdfbakjfbkafbafkjbafkjbafbk",
            "Execute Task 2",
            "Execute Task 3",
            "Execute Task 4",
            "Execute Task 5",
            "Execute Task 6",
            "Execute Task 7",
            "Execute Task 8",
            "Execute Task 9",
            "Execute Task 10",
            "Execute Task 11",
            "Execute Task 12",
            "Execute Task 13",
            "Execute Task 14",
            "Execute Task 15",
            "Execute Task 16",
            "Execute Task 17",
            "Execute Task 18",
            "Execute Task 19",
            "Execute Task 20",
            "Execute Task 21",
            "Execute Task 22",
            "Execute Task 23",
            "Execute Task 24",
        ],
    },
];

const APPROVE = [
    {
        title: "Approve",
        content: [
            "Approve Task 1",
            "Approve Task 2",
            "Approve Task 3",
            "Approve Task 4",
            "Approve Task 5",
            "Approve Task 6",
            "Approve Task 7",
            "Approve Task 8",
            "Approve Task 9",
            "Approve Task 10",
            "Approve Task 11",
            "Approve Task 12",
            "Approve Task 13",
            "Approve Task 14",
            "Approve Task 15",
            "Approve Task 16",
        ],
    },
];
